server:
  port: 8079

spring:
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://192.168.3.200:8066/lab-39-mysql?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
